# This workflow is used to create a lite release build of the OpenList frontend.
#
# This will:
#
# - Build the lite version of the application.
# - Upload the lite release assets to GitHub.
#
# # Usage
#
# This workflow can be triggered by:
#
# - Pushing a tag that matches the pattern `v[0-9]+.[0-9]+.[0-9]+*` (semver format).
# - Manually via the GitHub Actions UI.

name: Release Build

on:
  push:
  workflow_dispatch:


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: "22"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Build Release
      run: |
        mkdir -p output
        chmod +x build.sh
        ./build.sh --release --compress --lite --skip-i18n
        mv dist/openlist-frontend-dist-lite-v*.tar.gz output/
        mv dist/i18n.tar.gz output/
        ./build.sh --release --compress --skip-i18n
        mv dist/openlist-frontend-dist-v*.tar.gz output/
        echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-6)" >> $GITHUB_ENV

    - name: Upload Release Assets
      run: |
        gh release create \
          ${{ github.ref_name }} \
          --title "Release $SHORT_SHA" \
          --generate-notes \
          output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
